# github ci triggers doc:
# https://docs.microsoft.com/zh-cn/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - version.props

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  name: "build_to_nuget_pakcages"
  inputs:
    filePath: './nupkg/pack.ps1'
    pwsh: true
    workingDirectory: './nupkg'

- task: PowerShell@2
  name: "publish_to_nuget"
  inputs:
    filePath: './nupkg/push_packages.ps1'
    arguments: $(nuget_key)
    pwsh: true
    workingDirectory: './nupkg'